name: CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: |
        chmod +x gradlew
        ./gradlew build
        ls -ltrh

    - name: Run Unit Tests and Check Coverage
      run: |
        ./gradlew test
        ./gradlew build jacocoTestReport
        ls -ltrh
        ls -ltrh build
        ls -ltrh build/reports/jacoco/test/
        ls -ltrh build/jacocoHtml
        cat build/reports/jacoco/test/jacocoTestReport.xml
        echo -----
        echo -----
        cat build/jacocoHtml/index.html

    - name: Check Code Coverage
      run: |
        COVERAGE=$(cat build/jacocoHtml/index.html | grep -oP '</td><td class="ctr2">[^<]+' | grep -oP '[0-9]+')
        echo COVERAGE=$COVERAGE
        if [ "$COVERAGE" -lt 85 ]; then
          echo "Error: La cobertura de código es inferior al 85% (actual: $COVERAGE%)."
          exit 1
        fi